<script setup lang="ts">
import { ref, onMounted, watch } from 'vue'
import { storeToRefs } from 'pinia'
import { usePptTemplateStore } from '@renderer/stores'
import type { PptTemplateStatus } from '@shared/types/ppt-template'

interface Props {
  errorMessage?: string
  successMessage?: string
}

interface Emits {
  (e: 'update:errorMessage', value: string): void
  (e: 'update:successMessage', value: string): void
}

const props = defineProps<Props>()
const emit = defineEmits<Emits>()

// 使用 PPT 模板 Store
const pptTemplateStore = usePptTemplateStore()
const {
  sortedTemplates,
  loading,
  uploading,
  error: storeError,
  success: storeSuccess
} = storeToRefs(pptTemplateStore)

// UI 状态
const selectedFile = ref<File | null>(null)
const templateName = ref('')
const lastAutoGeneratedName = ref('') // 记录最后一次自动生成的名称

// 文件选择输入框引用
const fileInputRef = ref<HTMLInputElement | null>(null)

// 显示消息
function showError(message: string): void {
  emit('update:errorMessage', message)
}

function showSuccess(message: string): void {
  emit('update:successMessage', message)
  setTimeout(() => {
    emit('update:successMessage', '')
  }, 3000)
}

// 监听 Store 错误变化
watch(
  () => storeError.value,
  (newError) => {
    if (newError) {
      showError(newError)
      pptTemplateStore.clearError()
    }
  }
)

// 监听 Store 成功消息变化
watch(
  () => storeSuccess.value,
  (newSuccess) => {
    if (newSuccess) {
      showSuccess(newSuccess)
      pptTemplateStore.clearSuccess()
    }
  }
)

// 处理文件选择
function handleFileSelect(event: Event): void {
  const target = event.target as HTMLInputElement
  const file = target.files?.[0]
  if (!file) return

  // 验证文件扩展名
  if (!file.name.toLowerCase().endsWith('.pptx')) {
    showError('仅支持 .pptx 格式的文件')
    target.value = ''
    selectedFile.value = null
    return
  }

  // 验证文件大小（50MB 限制）
  const maxSize = 50 * 1024 * 1024
  if (file.size > maxSize) {
    showError('文件大小不能超过 50MB')
    target.value = ''
    selectedFile.value = null
    return
  }

  selectedFile.value = file

  // 如果名称为空或仍等于上一次自动生成的值，则刷新
  const baseName = file.name.replace(/\.pptx$/i, '')
  const autoName = `模板-${baseName}`

  if (!templateName.value.trim() || templateName.value === lastAutoGeneratedName.value) {
    templateName.value = autoName
    lastAutoGeneratedName.value = autoName
  }
}

// 点击文件选择按钮
function triggerFileSelect(): void {
  fileInputRef.value?.click()
}

// 上传模板
async function handleUpload(): Promise<void> {
  if (!selectedFile.value) {
    showError('请先选择文件')
    return
  }

  const name = templateName.value.trim()
  if (!name) {
    showError('请输入模板名称')
    return
  }

  const success = await pptTemplateStore.createTemplate(selectedFile.value, name)
  if (success) {
    // 重置表单
    selectedFile.value = null
    templateName.value = ''
    lastAutoGeneratedName.value = ''
    if (fileInputRef.value) {
      fileInputRef.value.value = ''
    }
  }
}

// 重置表单
function handleReset(): void {
  selectedFile.value = null
  templateName.value = ''
  lastAutoGeneratedName.value = ''
  if (fileInputRef.value) {
    fileInputRef.value.value = ''
  }
}

// 刷新列表
async function handleRefresh(): Promise<void> {
  await pptTemplateStore.refreshTemplates()
}

// 格式化文件大小
function formatFileSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`
}

// 格式化时间
function formatTime(dateString: string): string {
  const date = new Date(dateString)
  const now = new Date()
  const diff = now.getTime() - date.getTime()

  // 小于 1 小时
  if (diff < 60 * 60 * 1000) {
    const minutes = Math.floor(diff / (60 * 1000))
    return minutes < 1 ? '刚刚' : `${minutes} 分钟前`
  }

  // 小于 24 小时
  if (diff < 24 * 60 * 60 * 1000) {
    const hours = Math.floor(diff / (60 * 60 * 1000))
    return `${hours} 小时前`
  }

  // 小于 7 天
  if (diff < 7 * 24 * 60 * 60 * 1000) {
    const days = Math.floor(diff / (24 * 60 * 60 * 1000))
    return `${days} 天前`
  }

  // 显示完整日期
  return date.toLocaleDateString('zh-CN', {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit'
  })
}

// 获取状态文本
function getStatusText(status: PptTemplateStatus): string {
  switch (status) {
    case 'analyzing':
      return '分析中'
    case 'completed':
      return '分析完成'
    case 'failed':
      return '分析失败'
    default:
      return '未知'
  }
}

// 获取状态样式类
function getStatusClass(status: PptTemplateStatus): string {
  switch (status) {
    case 'analyzing':
      return 'status-analyzing'
    case 'completed':
      return 'status-completed'
    case 'failed':
      return 'status-failed'
    default:
      return ''
  }
}

// 组件挂载时加载模板列表
onMounted(() => {
  pptTemplateStore.loadTemplates()
})
</script>

<template>
  <div class="ppt-template-settings">
    <!-- 上传区域 -->
    <div class="upload-section">
      <div class="section-header">
        <h3 class="section-title">上传 PPT 模板</h3>
        <span class="section-hint">仅支持 .pptx 格式，文件大小不超过 50MB</span>
      </div>

      <div class="upload-form">
        <!-- 文件选择 -->
        <div class="form-group">
          <label class="form-label">选择文件</label>
          <div class="file-select-row">
            <button class="btn btn-secondary" @click="triggerFileSelect">选择文件</button>
            <span v-if="selectedFile" class="selected-file-name">
              {{ selectedFile.name }}
            </span>
            <span v-else class="file-placeholder">未选择文件</span>
          </div>
          <input
            ref="fileInputRef"
            type="file"
            accept=".pptx"
            class="hidden-input"
            @change="handleFileSelect"
          />
        </div>

        <!-- 模板名称 -->
        <div class="form-group">
          <label class="form-label" for="template-name">模板名称</label>
          <input
            id="template-name"
            v-model="templateName"
            type="text"
            class="form-input"
            placeholder="模板-文件名"
            :disabled="!selectedFile"
          />
          <span class="form-hint">保存后不可修改名称</span>
        </div>

        <!-- 操作按钮 -->
        <div class="form-actions">
          <button class="btn btn-secondary" :disabled="!selectedFile" @click="handleReset">
            重置
          </button>
          <button
            class="btn btn-primary"
            :disabled="!selectedFile || uploading"
            @click="handleUpload"
          >
            {{ uploading ? '上传中...' : '上传模板' }}
          </button>
        </div>
      </div>
    </div>

    <!-- 模板列表 -->
    <div class="template-list-section">
      <div class="section-header">
        <h3 class="section-title">模板列表</h3>
        <button class="btn-icon" @click="handleRefresh" title="刷新列表">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <path d="M23 4v6h-6M1 20v-6h6" />
            <path d="M3.51 9a9 9 0 0 1 14.85-3.36L23 10M1 14l4.64 4.36A9 9 0 0 0 20.49 15" />
          </svg>
        </button>
      </div>

      <div v-if="loading" class="loading-state">
        <span>加载中...</span>
      </div>

      <div v-else-if="sortedTemplates.length === 0" class="empty-state">
        <p>暂无模板，请上传您的第一个 PPT 模板</p>
      </div>

      <div v-else class="template-list">
        <div v-for="template in sortedTemplates" :key="template.id" class="template-item">
          <div class="template-header">
            <span class="template-name">{{ template.name }}</span>
            <span class="template-status" :class="getStatusClass(template.status)">
              {{ getStatusText(template.status) }}
            </span>
          </div>
          <div class="template-info">
            <span class="info-item">
              <span class="info-label">原文件:</span>
              <span class="info-value">{{ template.originalFileName }}</span>
            </span>
            <span class="info-item">
              <span class="info-label">页数:</span>
              <span class="info-value">{{ template.slideCount }}</span>
            </span>
            <span class="info-item">
              <span class="info-label">大小:</span>
              <span class="info-value">{{ formatFileSize(template.fileSize) }}</span>
            </span>
            <span class="info-item">
              <span class="info-label">上传时间:</span>
              <span class="info-value">{{ formatTime(template.createdAt) }}</span>
            </span>
          </div>
          <div v-if="template.status === 'completed'" class="template-analysis-path">
            <span class="path-label">分析结果:</span>
            <code class="path-value">{{ pptTemplateStore.getAnalysisPath(template.id) }}</code>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.ppt-template-settings {
  display: flex;
  flex-direction: column;
  gap: 24px;
}

/* 上传区域 */
.upload-section {
  padding: 16px;
  border: 1px solid var(--theme-border);
  border-radius: var(--theme-radius);
  background-color: var(--theme-bg-secondary);
}

.section-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 12px;
}

.section-title {
  font-size: 14px;
  font-weight: 600;
  color: var(--theme-text);
  margin: 0;
}

.section-hint {
  font-size: 12px;
  color: var(--theme-text-tertiary);
}

.upload-form {
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.form-group {
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.form-label {
  font-size: 13px;
  font-weight: 500;
  color: var(--theme-text);
}

.form-input {
  min-height: 38px;
  padding: 8px 12px;
  background-color: var(--theme-bg);
  border: 1px solid var(--theme-border);
  border-radius: var(--theme-radius-sm);
  color: var(--theme-text);
  font-size: 13px;
  transition: border-color 0.15s ease;
}

.form-input:hover:not(:disabled) {
  border-color: var(--theme-border-hover);
}

.form-input:focus {
  outline: none;
  border-color: var(--theme-accent);
}

.form-input:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}

.form-hint {
  font-size: 12px;
  color: var(--theme-text-tertiary);
}

.file-select-row {
  display: flex;
  align-items: center;
  gap: 12px;
}

.selected-file-name {
  font-size: 13px;
  color: var(--theme-text);
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.file-placeholder {
  font-size: 13px;
  color: var(--theme-text-tertiary);
}

.hidden-input {
  display: none;
}

/* 按钮 */
.form-actions {
  display: flex;
  gap: 12px;
}

.btn {
  min-height: 38px;
  padding: 8px 16px;
  font-size: 13px;
  font-weight: 500;
  font-family: var(--theme-font);
  border-radius: var(--theme-radius-sm);
  cursor: pointer;
  transition: all 0.15s ease;
}

.btn:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.btn-secondary {
  background-color: var(--theme-bg-secondary);
  border: 1px solid var(--theme-border);
  color: var(--theme-text);
}

.btn-secondary:hover:not(:disabled) {
  background-color: var(--theme-bg-tertiary);
  border-color: var(--theme-border-hover);
}

.btn-primary {
  background-color: var(--theme-accent);
  border: 1px solid var(--theme-accent);
  color: white;
}

.btn-primary:hover:not(:disabled) {
  opacity: 0.9;
}

/* 图标按钮 */
.btn-icon {
  width: 32px;
  height: 32px;
  padding: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  background: transparent;
  border: none;
  border-radius: var(--theme-radius-sm);
  cursor: pointer;
  color: var(--theme-text-secondary);
  transition: all 0.15s ease;
}

.btn-icon:hover {
  background-color: var(--theme-bg-secondary);
  color: var(--theme-text);
}

.btn-icon svg {
  width: 16px;
  height: 16px;
}

/* 模板列表 */
.template-list-section {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.loading-state,
.empty-state {
  text-align: center;
  padding: 32px;
  color: var(--theme-text-secondary);
  font-size: 13px;
}

.template-list {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.template-item {
  padding: 12px 16px;
  border: 1px solid var(--theme-border);
  border-radius: var(--theme-radius-sm);
  background-color: var(--theme-bg-secondary);
  transition: border-color 0.15s ease;
}

.template-item:hover {
  border-color: var(--theme-border-hover);
}

.template-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 8px;
}

.template-name {
  font-size: 14px;
  font-weight: 600;
  color: var(--theme-text);
}

.template-status {
  font-size: 12px;
  padding: 2px 8px;
  border-radius: 999px;
  font-weight: 500;
}

.status-analyzing {
  background-color: rgba(245, 158, 11, 0.1);
  color: #f59e0b;
}

.status-completed {
  background-color: rgba(34, 197, 94, 0.1);
  color: #22c55e;
}

.status-failed {
  background-color: rgba(239, 68, 68, 0.1);
  color: #ef4444;
}

.template-info {
  display: flex;
  flex-wrap: wrap;
  gap: 16px;
  font-size: 12px;
}

.info-item {
  display: flex;
  gap: 4px;
}

.info-label {
  color: var(--theme-text-tertiary);
}

.info-value {
  color: var(--theme-text-secondary);
}

.template-analysis-path {
  margin-top: 8px;
  padding-top: 8px;
  border-top: 1px solid var(--theme-border);
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 12px;
}

.path-label {
  color: var(--theme-text-tertiary);
  white-space: nowrap;
}

.path-value {
  font-family: var(--theme-font-mono, monospace);
  font-size: 11px;
  color: var(--theme-text-secondary);
  background-color: var(--theme-bg);
  padding: 2px 6px;
  border-radius: 4px;
  overflow: hidden;
  text-overflow: ellipsis;
}
</style>
