<script setup lang="ts">
import { ref, onMounted, watch } from 'vue'
import { storeToRefs } from 'pinia'
import { usePptTemplateStore } from '@renderer/stores'
import type { PptTemplateStatus } from '@shared/types/ppt-template'

interface Props {
  errorMessage?: string
  successMessage?: string
}

interface Emits {
  (e: 'update:errorMessage', value: string): void
  (e: 'update:successMessage', value: string): void
}

defineProps<Props>()
const emit = defineEmits<Emits>()

// 使用 PPT 模板 Store
const pptTemplateStore = usePptTemplateStore()
const {
  sortedTemplates,
  loading,
  uploading,
  error: storeError,
  success: storeSuccess
} = storeToRefs(pptTemplateStore)

// UI 状态
const selectedFile = ref<File | null>(null)
const templateName = ref('')
const lastAutoGeneratedName = ref('') // 记录最后一次自动生成的名称
const isDragging = ref(false) // 拖拽状态
const deletingId = ref<string | null>(null) // 正在删除的模板 ID

// 文件选择输入框引用
const fileInputRef = ref<HTMLInputElement | null>(null)

// 显示消息
function showError(message: string): void {
  emit('update:errorMessage', message)
}

function showSuccess(message: string): void {
  emit('update:successMessage', message)
  setTimeout(() => {
    emit('update:successMessage', '')
  }, 3000)
}

// 监听 Store 错误变化
watch(
  () => storeError.value,
  (newError) => {
    if (newError) {
      showError(newError)
      pptTemplateStore.clearError()
    }
  }
)

// 监听 Store 成功消息变化
watch(
  () => storeSuccess.value,
  (newSuccess) => {
    if (newSuccess) {
      showSuccess(newSuccess)
      pptTemplateStore.clearSuccess()
    }
  }
)

// 验证文件
function validateFile(file: File): boolean {
  // 验证文件扩展名
  if (!file.name.toLowerCase().endsWith('.pptx')) {
    showError('仅支持 .pptx 格式的文件')
    return false
  }

  // 验证文件大小（50MB 限制）
  const maxSize = 50 * 1024 * 1024
  if (file.size > maxSize) {
    showError('文件大小不能超过 50MB')
    return false
  }

  return true
}

// 处理文件
function processFile(file: File): void {
  selectedFile.value = file

  // 如果名称为空或仍等于上一次自动生成的值，则刷新
  const baseName = file.name.replace(/\.pptx$/i, '')
  const autoName = `模板-${baseName}`

  if (!templateName.value.trim() || templateName.value === lastAutoGeneratedName.value) {
    templateName.value = autoName
    lastAutoGeneratedName.value = autoName
  }
}

// 处理文件选择
function handleFileSelect(event: Event): void {
  const target = event.target as HTMLInputElement
  const file = target.files?.[0]
  if (!file) return

  if (validateFile(file)) {
    processFile(file)
  } else {
    target.value = ''
    selectedFile.value = null
  }
}

// 点击上传区域
function triggerFileSelect(): void {
  fileInputRef.value?.click()
}

// 拖拽进入
function handleDragEnter(event: DragEvent): void {
  event.preventDefault()
  event.stopPropagation()
  isDragging.value = true
}

// 拖拽离开
function handleDragLeave(event: DragEvent): void {
  event.preventDefault()
  event.stopPropagation()
  isDragging.value = false
}

// 拖拽悬停
function handleDragOver(event: DragEvent): void {
  event.preventDefault()
  event.stopPropagation()
}

// 拖拽放下
function handleDrop(event: DragEvent): void {
  event.preventDefault()
  event.stopPropagation()
  isDragging.value = false

  const files = event.dataTransfer?.files
  if (!files || files.length === 0) return

  const file = files[0]
  if (validateFile(file)) {
    processFile(file)
  }
}

// 上传模板
async function handleUpload(): Promise<void> {
  if (!selectedFile.value) {
    showError('请先选择文件')
    return
  }

  const name = templateName.value.trim()
  if (!name) {
    showError('请输入模板名称')
    return
  }

  const success = await pptTemplateStore.createTemplate(selectedFile.value, name)
  if (success) {
    // 重置表单
    selectedFile.value = null
    templateName.value = ''
    lastAutoGeneratedName.value = ''
    if (fileInputRef.value) {
      fileInputRef.value.value = ''
    }
  }
}

// 重置表单
function handleReset(): void {
  selectedFile.value = null
  templateName.value = ''
  lastAutoGeneratedName.value = ''
  if (fileInputRef.value) {
    fileInputRef.value.value = ''
  }
}

// 删除模板
async function handleDelete(templateId: string, templateName: string): Promise<void> {
  // 确认删除
  const confirmed = window.confirm(`确定要删除模板 "${templateName}" 吗？\n\n删除后将无法恢复。`)
  if (!confirmed) return

  deletingId.value = templateId
  try {
    await pptTemplateStore.deleteTemplate(templateId)
  } finally {
    deletingId.value = null
  }
}

// 刷新列表
async function handleRefresh(): Promise<void> {
  await pptTemplateStore.refreshTemplates()
}

// 格式化文件大小
function formatFileSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`
}

// 格式化时间
function formatTime(dateString: string): string {
  const date = new Date(dateString)
  const now = new Date()
  const diff = now.getTime() - date.getTime()

  // 小于 1 小时
  if (diff < 60 * 60 * 1000) {
    const minutes = Math.floor(diff / (60 * 1000))
    return minutes < 1 ? '刚刚' : `${minutes} 分钟前`
  }

  // 小于 24 小时
  if (diff < 24 * 60 * 60 * 1000) {
    const hours = Math.floor(diff / (60 * 60 * 1000))
    return `${hours} 小时前`
  }

  // 小于 7 天
  if (diff < 7 * 24 * 60 * 60 * 1000) {
    const days = Math.floor(diff / (24 * 60 * 60 * 1000))
    return `${days} 天前`
  }

  // 显示完整日期
  return date.toLocaleDateString('zh-CN', {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit'
  })
}

// 获取状态文本
function getStatusText(status: PptTemplateStatus): string {
  switch (status) {
    case 'analyzing':
      return '分析中'
    case 'completed':
      return '分析完成'
    case 'failed':
      return '分析失败'
    default:
      return '未知'
  }
}

// 获取状态样式类
function getStatusClass(status: PptTemplateStatus): string {
  switch (status) {
    case 'analyzing':
      return 'status-analyzing'
    case 'completed':
      return 'status-completed'
    case 'failed':
      return 'status-failed'
    default:
      return ''
  }
}

// 组件挂载时加载模板列表
onMounted(() => {
  pptTemplateStore.loadTemplates()
})
</script>

<template>
  <div class="ppt-template-settings">
    <!-- 上传区域 -->
    <div class="upload-section">
      <div class="section-header">
        <h3 class="section-title">上传 PPT 模板</h3>
      </div>

      <!-- 拖拽上传区域 -->
      <div
        class="upload-dropzone"
        :class="{
          'is-dragging': isDragging,
          'has-file': selectedFile
        }"
        @click="triggerFileSelect"
        @dragenter="handleDragEnter"
        @dragleave="handleDragLeave"
        @dragover="handleDragOver"
        @drop="handleDrop"
      >
        <input
          ref="fileInputRef"
          type="file"
          accept=".pptx"
          class="hidden-input"
          @change="handleFileSelect"
        />

        <!-- 未选择文件时的状态 -->
        <div v-if="!selectedFile" class="dropzone-content">
          <div class="upload-icon">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
              <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
              <polyline points="17 8 12 3 7 8" />
              <line x1="12" y1="3" x2="12" y2="15" />
            </svg>
          </div>
          <div class="upload-text">
            <p class="upload-title">拖拽文件到此处，或 <span class="upload-link">点击上传</span></p>
            <p class="upload-hint">支持 .pptx 格式，最大 50MB</p>
          </div>
        </div>

        <!-- 已选择文件时的状态 -->
        <div v-else class="dropzone-file-info">
          <div class="file-icon">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
              <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
              <polyline points="14 2 14 8 20 8" />
              <line x1="16" y1="13" x2="8" y2="13" />
              <line x1="16" y1="17" x2="8" y2="17" />
              <polyline points="10 9 9 9 8 9" />
            </svg>
          </div>
          <div class="file-details">
            <p class="file-name">{{ selectedFile.name }}</p>
            <p class="file-size">{{ formatFileSize(selectedFile.size) }}</p>
          </div>
          <button class="btn-remove" title="移除文件" @click.stop="handleReset">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <line x1="18" y1="6" x2="6" y2="18" />
              <line x1="6" y1="6" x2="18" y2="18" />
            </svg>
          </button>
        </div>
      </div>

      <!-- 模板名称输入（文件选择后显示） -->
      <div v-if="selectedFile" class="upload-form-footer">
        <div class="form-group">
          <label class="form-label" for="template-name">模板名称</label>
          <div class="form-row">
            <input
              id="template-name"
              v-model="templateName"
              type="text"
              class="form-input"
              placeholder="输入模板名称"
            />
            <button
              class="btn btn-primary"
              :disabled="!templateName.trim() || uploading"
              @click="handleUpload"
            >
              <span v-if="uploading" class="btn-loading">
                <svg class="spinner" viewBox="0 0 24 24">
                  <circle
                    cx="12"
                    cy="12"
                    r="10"
                    stroke="currentColor"
                    stroke-width="3"
                    fill="none"
                    stroke-dasharray="31.4 31.4"
                  />
                </svg>
                上传中
              </span>
              <span v-else>上传模板</span>
            </button>
          </div>
          <span class="form-hint">保存后不可修改名称</span>
        </div>
      </div>
    </div>

    <!-- 模板列表 -->
    <div class="template-list-section">
      <div class="section-header">
        <h3 class="section-title">模板列表</h3>
        <button class="btn-icon" title="刷新列表" @click="handleRefresh">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <path d="M23 4v6h-6M1 20v-6h6" />
            <path d="M3.51 9a9 9 0 0 1 14.85-3.36L23 10M1 14l4.64 4.36A9 9 0 0 0 20.49 15" />
          </svg>
        </button>
      </div>

      <div v-if="loading" class="loading-state">
        <span>加载中...</span>
      </div>

      <div v-else-if="sortedTemplates.length === 0" class="empty-state">
        <p>暂无模板，请上传您的第一个 PPT 模板</p>
      </div>

      <div v-else class="template-list">
        <div v-for="template in sortedTemplates" :key="template.id" class="template-item">
          <div class="template-header">
            <span class="template-name">{{ template.name }}</span>
            <div class="template-actions">
              <span class="template-status" :class="getStatusClass(template.status)">
                {{ getStatusText(template.status) }}
              </span>
              <button
                class="btn-delete"
                title="删除模板"
                :disabled="deletingId === template.id"
                @click="handleDelete(template.id, template.name)"
              >
                <svg v-if="deletingId === template.id" class="spinner-small" viewBox="0 0 24 24">
                  <circle
                    cx="12"
                    cy="12"
                    r="10"
                    stroke="currentColor"
                    stroke-width="3"
                    fill="none"
                    stroke-dasharray="31.4 31.4"
                  />
                </svg>
                <svg v-else viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                  <polyline points="3 6 5 6 21 6" />
                  <path
                    d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"
                  />
                  <line x1="10" y1="11" x2="10" y2="17" />
                  <line x1="14" y1="11" x2="14" y2="17" />
                </svg>
              </button>
            </div>
          </div>
          <div class="template-info">
            <span class="info-item">
              <span class="info-label">原文件:</span>
              <span class="info-value">{{ template.originalFileName }}</span>
            </span>
            <span class="info-item">
              <span class="info-label">页数:</span>
              <span class="info-value">{{ template.slideCount }}</span>
            </span>
            <span class="info-item">
              <span class="info-label">大小:</span>
              <span class="info-value">{{ formatFileSize(template.fileSize) }}</span>
            </span>
            <span class="info-item">
              <span class="info-label">上传时间:</span>
              <span class="info-value">{{ formatTime(template.createdAt) }}</span>
            </span>
          </div>
          <div v-if="template.status === 'completed'" class="template-analysis-path">
            <span class="path-label">分析结果:</span>
            <code class="path-value">{{ pptTemplateStore.getAnalysisPath(template.id) }}</code>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.ppt-template-settings {
  display: flex;
  flex-direction: column;
  gap: 24px;
}

/* 上传区域 */
.upload-section {
  padding: 16px;
  border: 1px solid var(--theme-border);
  border-radius: var(--theme-radius);
  background-color: var(--theme-bg-secondary);
}

.section-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 12px;
}

.section-title {
  font-size: 14px;
  font-weight: 600;
  color: var(--theme-text);
  margin: 0;
}

/* 拖拽上传区域 */
.upload-dropzone {
  position: relative;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  min-height: 140px;
  padding: 24px;
  border: 2px dashed var(--theme-border);
  border-radius: var(--theme-radius);
  background-color: var(--theme-bg);
  cursor: pointer;
  transition: all 0.2s ease;
}

.upload-dropzone:hover {
  border-color: var(--theme-accent);
  background-color: rgba(var(--theme-accent-rgb, 59 130 246), 0.02);
}

.upload-dropzone.is-dragging {
  border-color: var(--theme-accent);
  background-color: rgba(var(--theme-accent-rgb, 59 130 246), 0.05);
  transform: scale(1.01);
}

.upload-dropzone.has-file {
  border-style: solid;
  border-color: var(--theme-accent);
  background-color: rgba(var(--theme-accent-rgb, 59 130 246), 0.02);
}

.hidden-input {
  position: absolute;
  width: 0;
  height: 0;
  opacity: 0;
  pointer-events: none;
}

/* 拖拽区域内容 */
.dropzone-content {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 12px;
  text-align: center;
}

.upload-icon {
  width: 48px;
  height: 48px;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: var(--theme-bg-secondary);
  border-radius: 50%;
  color: var(--theme-accent);
}

.upload-icon svg {
  width: 24px;
  height: 24px;
}

.upload-text {
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.upload-title {
  font-size: 14px;
  color: var(--theme-text);
  margin: 0;
}

.upload-link {
  color: var(--theme-accent);
  font-weight: 500;
}

.upload-hint {
  font-size: 12px;
  color: var(--theme-text-tertiary);
  margin: 0;
}

/* 已选文件信息 */
.dropzone-file-info {
  display: flex;
  align-items: center;
  gap: 12px;
  width: 100%;
  padding: 8px;
}

.file-icon {
  width: 40px;
  height: 40px;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: var(--theme-bg-secondary);
  border-radius: var(--theme-radius-sm);
  color: var(--theme-accent);
  flex-shrink: 0;
}

.file-icon svg {
  width: 20px;
  height: 20px;
}

.file-details {
  flex: 1;
  min-width: 0;
}

.file-name {
  font-size: 14px;
  font-weight: 500;
  color: var(--theme-text);
  margin: 0;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.file-size {
  font-size: 12px;
  color: var(--theme-text-tertiary);
  margin: 4px 0 0 0;
}

.btn-remove {
  width: 32px;
  height: 32px;
  display: flex;
  align-items: center;
  justify-content: center;
  background: transparent;
  border: none;
  border-radius: var(--theme-radius-sm);
  cursor: pointer;
  color: var(--theme-text-tertiary);
  transition: all 0.15s ease;
  flex-shrink: 0;
}

.btn-remove:hover {
  background-color: rgba(239, 68, 68, 0.1);
  color: #ef4444;
}

.btn-remove svg {
  width: 16px;
  height: 16px;
}

/* 上传表单底部 */
.upload-form-footer {
  margin-top: 16px;
  padding-top: 16px;
  border-top: 1px solid var(--theme-border);
}

.form-group {
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.form-label {
  font-size: 13px;
  font-weight: 500;
  color: var(--theme-text);
}

.form-row {
  display: flex;
  gap: 12px;
}

.form-input {
  flex: 1;
  min-height: 38px;
  padding: 8px 12px;
  background-color: var(--theme-bg);
  border: 1px solid var(--theme-border);
  border-radius: var(--theme-radius-sm);
  color: var(--theme-text);
  font-size: 13px;
  transition: border-color 0.15s ease;
}

.form-input:hover:not(:disabled) {
  border-color: var(--theme-border-hover);
}

.form-input:focus {
  outline: none;
  border-color: var(--theme-accent);
}

.form-hint {
  font-size: 12px;
  color: var(--theme-text-tertiary);
}

/* 按钮 */
.btn {
  min-height: 38px;
  padding: 8px 16px;
  font-size: 13px;
  font-weight: 500;
  font-family: var(--theme-font);
  border-radius: var(--theme-radius-sm);
  cursor: pointer;
  transition: all 0.15s ease;
  white-space: nowrap;
}

.btn:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.btn-primary {
  background-color: var(--theme-accent);
  border: 1px solid var(--theme-accent);
  color: white;
}

.btn-primary:hover:not(:disabled) {
  opacity: 0.9;
}

.btn-loading {
  display: flex;
  align-items: center;
  gap: 6px;
}

.spinner {
  width: 14px;
  height: 14px;
  animation: spin 1s linear infinite;
}

@keyframes spin {
  from {
    transform: rotate(0deg);
  }
  to {
    transform: rotate(360deg);
  }
}

/* 图标按钮 */
.btn-icon {
  width: 32px;
  height: 32px;
  padding: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  background: transparent;
  border: none;
  border-radius: var(--theme-radius-sm);
  cursor: pointer;
  color: var(--theme-text-secondary);
  transition: all 0.15s ease;
}

.btn-icon:hover {
  background-color: var(--theme-bg-secondary);
  color: var(--theme-text);
}

.btn-icon svg {
  width: 16px;
  height: 16px;
}

/* 模板列表 */
.template-list-section {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.loading-state,
.empty-state {
  text-align: center;
  padding: 32px;
  color: var(--theme-text-secondary);
  font-size: 13px;
}

.template-list {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.template-item {
  padding: 12px 16px;
  border: 1px solid var(--theme-border);
  border-radius: var(--theme-radius-sm);
  background-color: var(--theme-bg-secondary);
  transition: border-color 0.15s ease;
}

.template-item:hover {
  border-color: var(--theme-border-hover);
}

.template-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
  margin-bottom: 8px;
}

.template-name {
  font-size: 14px;
  font-weight: 600;
  color: var(--theme-text);
  flex: 1;
  min-width: 0;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.template-status {
  font-size: 12px;
  padding: 2px 8px;
  border-radius: 999px;
  font-weight: 500;
  flex-shrink: 0;
}

.template-actions {
  display: flex;
  align-items: center;
  gap: 8px;
  flex-shrink: 0;
}

.btn-delete {
  width: 28px;
  height: 28px;
  display: flex;
  align-items: center;
  justify-content: center;
  background: transparent;
  border: none;
  border-radius: var(--theme-radius-sm);
  cursor: pointer;
  color: var(--theme-text-tertiary);
  transition: all 0.15s ease;
}

.btn-delete:hover:not(:disabled) {
  background-color: rgba(239, 68, 68, 0.1);
  color: #ef4444;
}

.btn-delete:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.btn-delete svg {
  width: 14px;
  height: 14px;
}

.spinner-small {
  width: 14px;
  height: 14px;
  animation: spin 1s linear infinite;
}

.status-analyzing {
  background-color: rgba(245, 158, 11, 0.1);
  color: #f59e0b;
}

.status-completed {
  background-color: rgba(34, 197, 94, 0.1);
  color: #22c55e;
}

.status-failed {
  background-color: rgba(239, 68, 68, 0.1);
  color: #ef4444;
}

.template-info {
  display: flex;
  flex-wrap: wrap;
  gap: 16px;
  font-size: 12px;
}

.info-item {
  display: flex;
  gap: 4px;
}

.info-label {
  color: var(--theme-text-tertiary);
}

.info-value {
  color: var(--theme-text-secondary);
}

.template-analysis-path {
  margin-top: 8px;
  padding-top: 8px;
  border-top: 1px solid var(--theme-border);
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 12px;
}

.path-label {
  color: var(--theme-text-tertiary);
  white-space: nowrap;
}

.path-value {
  font-family: var(--theme-font-mono, monospace);
  font-size: 11px;
  color: var(--theme-text-secondary);
  background-color: var(--theme-bg);
  padding: 2px 6px;
  border-radius: 4px;
  overflow: hidden;
  text-overflow: ellipsis;
}
</style>
