import { ref, watch, type Ref } from 'vue'
import { storeToRefs } from 'pinia'
import { usePptTemplateStore } from '@renderer/stores'

/**
 * 模板上传逻辑 composable
 * 处理文件选择、验证、拖拽和上传
 */
export function useTemplateUpload(
  onError: (msg: string) => void,
  onSuccess: (msg: string) => void
) {
  const pptTemplateStore = usePptTemplateStore()
  const { uploading } = storeToRefs(pptTemplateStore)

  // UI 状态
  const selectedFile = ref<File | null>(null)
  const templateName = ref('')
  const lastAutoGeneratedName = ref('')
  const isDragging = ref(false)

  // 监听 Store 成功消息
  watch(
    () => pptTemplateStore.success,
    (newSuccess) => {
      if (newSuccess) {
        onSuccess(newSuccess)
        pptTemplateStore.clearSuccess()
      }
    }
  )

  // 监听 Store 错误
  watch(
    () => pptTemplateStore.error,
    (newError) => {
      if (newError) {
        onError(newError)
        pptTemplateStore.clearError()
      }
    }
  )

  /** 验证文件 */
  function validateFile(file: File): boolean {
    if (!file.name.toLowerCase().endsWith('.pptx')) {
      onError('仅支持 .pptx 格式的文件')
      return false
    }

    const maxSize = 50 * 1024 * 1024
    if (file.size > maxSize) {
      onError('文件大小不能超过 50MB')
      return false
    }

    return true
  }

  /** 处理文件 */
  function processFile(file: File): void {
    selectedFile.value = file

    const baseName = file.name.replace(/\.pptx$/i, '')
    const autoName = `模板-${baseName}`

    if (!templateName.value.trim() || templateName.value === lastAutoGeneratedName.value) {
      templateName.value = autoName
      lastAutoGeneratedName.value = autoName
    }
  }

  /** 处理文件选择 */
  function handleFileSelect(event: Event): void {
    const target = event.target as HTMLInputElement
    const file = target.files?.[0]

    if (!file) {
      target.value = ''
      return
    }

    if (validateFile(file)) {
      processFile(file)
    } else {
      selectedFile.value = null
    }

    // 每次选择完毕后清空 input 的值，确保下次选择同一文件能触发 change 事件
    target.value = ''
  }

  /** 创建点击上传区域函数（接收 fileInputRef） */
  function createTriggerFileSelect(fileInputRef: Ref<HTMLInputElement | null>): () => void {
    return () => fileInputRef.value?.click()
  }

  /** 拖拽进入 */
  function handleDragEnter(event: DragEvent): void {
    event.preventDefault()
    event.stopPropagation()
    isDragging.value = true
  }

  /** 拖拽离开 */
  function handleDragLeave(event: DragEvent): void {
    event.preventDefault()
    event.stopPropagation()
    isDragging.value = false
  }

  /** 拖拽悬停 */
  function handleDragOver(event: DragEvent): void {
    event.preventDefault()
    event.stopPropagation()
  }

  /** 拖拽放下 */
  function handleDrop(event: DragEvent): void {
    event.preventDefault()
    event.stopPropagation()
    isDragging.value = false

    const files = event.dataTransfer?.files
    if (!files || files.length === 0) return

    const file = files[0]
    if (validateFile(file)) {
      processFile(file)
    }
  }

  /** 上传模板 */
  async function handleUpload(): Promise<boolean> {
    if (!selectedFile.value) {
      onError('请先选择文件')
      return false
    }

    const name = templateName.value.trim()
    if (!name) {
      onError('请输入模板名称')
      return false
    }

    const success = await pptTemplateStore.createTemplate(selectedFile.value, name)
    if (success) {
      resetForm()
    }
    return success
  }

  /** 重置表单状态 */
  function resetForm(): void {
    selectedFile.value = null
    templateName.value = ''
    lastAutoGeneratedName.value = ''
  }

  /** 创建重置表单函数（接收 fileInputRef） */
  function createResetForm(fileInputRef: Ref<HTMLInputElement | null>): () => void {
    return () => {
      resetForm()
      if (fileInputRef.value) {
        fileInputRef.value.value = ''
      }
    }
  }

  /** 格式化文件大小 */
  function formatFileSize(bytes: number): string {
    if (bytes < 1024) return `${bytes} B`
    if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`
    return `${(bytes / (1024 * 1024)).toFixed(1)} MB`
  }

  return {
    // 状态
    selectedFile,
    templateName,
    isDragging,
    uploading,

    // 方法
    validateFile,
    processFile,
    handleFileSelect,
    createTriggerFileSelect,
    handleDragEnter,
    handleDragLeave,
    handleDragOver,
    handleDrop,
    handleUpload,
    resetForm,
    createResetForm,
    formatFileSize
  }
}
